features:
  - nitrogen
  - phosphorous
  - potassium
  - temperature
  - humidity
  - moisture
  - soil_type

data:
  dataset_path: data/soil_crop_dataset.csv

hyperparams:
  n_estimators: 100
  max_depth: 10
  random_state: 42
